// <auto-generated />
using System;
using DBConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBConnection.Migrations
{
    [DbContext(typeof(RamssisCleaningContex))]
    [Migration("20260323021226_ajoutdetablelog")]
    partial class ajoutdetablelog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBConnection.Entity.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("civicNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DBConnection.Entity.BillDescription", b =>
                {
                    b.Property<Guid>("BillDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("SubTotalPrice")
                        .HasColumnType("real");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("BillDescriptionId");

                    b.HasIndex("BillHistoryId");

                    b.ToTable("BillDescriptions");
                });

            modelBuilder.Entity("DBConnection.Entity.BillHistory", b =>
                {
                    b.Property<int>("billIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("billIdentifier"));

                    b.Property<string>("AfterSendedBillPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillDescriptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillHistoryNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BilledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("bit");

                    b.Property<bool?>("Issended")
                        .HasColumnType("bit");

                    b.Property<string>("MouthBill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfVisite")
                        .HasColumnType("int");

                    b.Property<float>("TPS")
                        .HasColumnType("real");

                    b.Property<float>("TVQ")
                        .HasColumnType("real");

                    b.Property<float>("TotalWithOutTax")
                        .HasColumnType("real");

                    b.Property<float>("TotalWithTax")
                        .HasColumnType("real");

                    b.Property<string>("compagnyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compagnyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("compagnyPrice")
                        .HasColumnType("real");

                    b.HasKey("billIdentifier");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("BillHistories");
                });

            modelBuilder.Entity("DBConnection.Entity.Client", b =>
                {
                    b.Property<Guid>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientID");

                    b.HasIndex("CompanyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DBConnection.Entity.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMailCredentiel")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TPSNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TVQNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int");

                    b.Property<string>("companyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("companyStatus")
                        .HasColumnType("bit");

                    b.Property<string>("prividercode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DBConnection.Entity.CompanyAddress", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("CompanyAddresses", (string)null);
                });

            modelBuilder.Entity("DBConnection.Entity.CompanyPricingCalendar", b =>
                {
                    b.Property<Guid>("CompanyPricingCalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CopagnyBenifictPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaysStatus")
                        .HasColumnType("bit");

                    b.Property<decimal>("Emplyeepaiment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CompanyPricingCalendarId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyPricingCalendars");
                });

            modelBuilder.Entity("DBConnection.Entity.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeAddress", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("EmployeeAddresses", (string)null);
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeCompagnyPricing", b =>
                {
                    b.Property<Guid>("EmployeeCompagnyPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyPricingCalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EmplyeePaiment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeCompagnyPricingId");

                    b.ToTable("EmployeeCompagnyPricings");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeCompany", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("EmployeeCompanies");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeCredential", b =>
                {
                    b.Property<int>("EmployeeCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCredentialId"));

                    b.Property<Guid>("EmplyeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeCredentialId");

                    b.ToTable("EmployeeCredentials");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeTimeLog", b =>
                {
                    b.Property<Guid>("EmployeeTimeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BeginWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ClientPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkType1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Workdate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeTimeLogId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTimeLogs");
                });

            modelBuilder.Entity("DBConnection.Entity.Mail.MailCredential", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("smtpPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("smtpPort")
                        .HasColumnType("int");

                    b.Property<string>("smtpServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smtpUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("MailCredentials");
                });

            modelBuilder.Entity("DBConnection.Entity.Provider", b =>
                {
                    b.Property<Guid>("providerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("providerID");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("DBConnection.Entity.Work", b =>
                {
                    b.Property<Guid>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BeginWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ClientPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndWorkDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkType1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Workdate")
                        .HasColumnType("date");

                    b.HasKey("WorkId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("DBConnection.Entity.WorkType", b =>
                {
                    b.Property<int>("WorkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkTypeId");

                    b.ToTable("WorkTypes");

                    b.HasData(
                        new
                        {
                            WorkTypeId = 1,
                            Name = "Par visite"
                        },
                        new
                        {
                            WorkTypeId = 2,
                            Name = "Hebdomadaire"
                        },
                        new
                        {
                            WorkTypeId = 3,
                            Name = "Bi-hebdomadaire"
                        },
                        new
                        {
                            WorkTypeId = 4,
                            Name = "Bi-mensuel"
                        },
                        new
                        {
                            WorkTypeId = 5,
                            Name = "Mensuel"
                        },
                        new
                        {
                            WorkTypeId = 6,
                            Name = "Horaire"
                        });
                });

            modelBuilder.Entity("DBConnection.Entity.BillDescription", b =>
                {
                    b.HasOne("DBConnection.Entity.BillHistory", "BillHistoris")
                        .WithMany("BillDescriptions")
                        .HasForeignKey("BillHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillHistoris");
                });

            modelBuilder.Entity("DBConnection.Entity.Client", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBConnection.Entity.Company", b =>
                {
                    b.HasOne("DBConnection.Entity.WorkType", "WorkType")
                        .WithMany("Companies")
                        .HasForeignKey("WorkTypeId");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("DBConnection.Entity.CompanyAddress", b =>
                {
                    b.HasOne("DBConnection.Entity.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBConnection.Entity.CompanyPricingCalendar", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany("CompanyPricingCalendars")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeAddress", b =>
                {
                    b.HasOne("DBConnection.Entity.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBConnection.Entity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeCompany", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany("EmployeeCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBConnection.Entity.Employee", "Employee")
                        .WithMany("EmployeeCompanies")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBConnection.Entity.EmployeeTimeLog", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBConnection.Entity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBConnection.Entity.Mail.MailCredential", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithOne("MailCredential")
                        .HasForeignKey("DBConnection.Entity.Mail.MailCredential", "CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBConnection.Entity.Work", b =>
                {
                    b.HasOne("DBConnection.Entity.Company", "Company")
                        .WithMany("Works")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBConnection.Entity.Employee", "Employee")
                        .WithMany("Works")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DBConnection.Entity.BillHistory", b =>
                {
                    b.Navigation("BillDescriptions");
                });

            modelBuilder.Entity("DBConnection.Entity.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("CompanyPricingCalendars");

                    b.Navigation("EmployeeCompanies");

                    b.Navigation("MailCredential")
                        .IsRequired();

                    b.Navigation("Works");
                });

            modelBuilder.Entity("DBConnection.Entity.Employee", b =>
                {
                    b.Navigation("EmployeeCompanies");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("DBConnection.Entity.WorkType", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
